### ISSUE TITLE
Crash on Viewing a receipe 

### ISSUE THREAD

**Issue by Motytheultimate** [dries007/TFCraft-NEIplugin#5]
If i click a receipe it crashes me 
http://pastebin.com/jY6kcJPa

**Comment by dries007** [comment]
You are most likly using an outdated or too new version of the mod. Can you
tell us what the versions are? TFC and the plugin please.

**Comment by Motytheultimate** [comment]
tfc is verions 0.79.15.538 and the plugin is 1.3.0.17
