### ISSUE TITLE
Crucible showing small tetrahedrite melting into silver

### ISSUE THREAD

**Issue by AnodeCathode** [dries007/TFCraft-NEIplugin#6]
Only shows in the crucible recipes. Doesn't in-fact happen in-game. 

This is with 79.25 (of course our TNFC version) and terrafirmacraftneiplugin-1.7.10-1.5.3.24

Come to #Technode @ Espernet if you want to chat about it :)

**Comment by dries007** [comment]
Hmm, I wonder how that happened...
