### ISSUE TITLE
StackOverflow crash, updating screen events when trying to view food recipes from TFC

### ISSUE THREAD

**Issue by NEXUS2345** [dries007/TFCraft-NEIplugin#7]
Crash report: http://pastebin.com/uMV3jQDk

Tested with our custom modpack (Prelude TFC on Technic launcher) and with just NEI, TFC and the plugin. Can be replicated by pressing U on any food item in NEI. Versions are NEI 1.0.5.118, TFC 0.79.26.882, NEI plugin 1.5.3.24.

**Comment by dries007** [comment]
Known bug in TFC, fixed by Deadrik/TFCraft@08c5990e02a7bfd97eade4f920c4505405411f16

**Comment by NEXUS2345** [comment]
Small issue there, this is happening in the latest version of TFC and there are no newer versions available...

**Comment by dries007** [comment]
I know, its not "a big enough problem" to warrant a new release of TFC, take that up with Kitty
